# Generated by Django 4.1.4 on 2022-12-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimages",
            name="image",
            field=models.ImageField(
                default="images/default.pnp",
                help_text="Upload a product image",
                upload_to="images/",
                verbose_name="image",
            ),
        ),
    ]
