# Generated by Django 4.1.4 on 2022-12-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_remove_comment_parent_comment_reply_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="articles.comment",
            ),
        ),
    ]
