# Generated by Django 4.1.4 on 2022-12-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follower",
            old_name="following_user",
            new_name="follower",
        ),
    ]
